services:

  mongodb:
    image: mongo:6
    container_name: mongodb_casa
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - sim_net

  mongo-express:
    image: mongo-express
    container_name: mongo_express_gui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb   # ⚠️ Ici c'est le nom du SERVICE, pas container_name
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongodb
    networks:
      - sim_net

  backend:
    build: ./backend
    container_name: backend_sim
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongodb
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      SUMO_HOME: /usr/share/sumo
      MONGO_URI: mongodb://mongodb:27017   # ⚠️ Utilise le nom du SERVICE
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/src/maps:/app/src/maps
      
    restart: unless-stopped
    networks:
      - sim_net

  frontend:
    build: ./frontend
    container_name: frontend_sim
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:8000
      WATCHPACK_POLLING: true
    restart: unless-stopped
    networks:
      - sim_net

volumes:
  mongo_data:

networks:
  sim_net:
    driver: bridge